DIRECT type support
busfor/react-native-google-pay pull request #15
Opened 2020-02-11 11:37 UTC by sorokin0andrey

2020-02-11 11:47 UTC, isokolovskii requested changes

2020-02-11 11:47 UTC, ivan3177 commented on index.d.ts
>      }
May be it's better not to put comment here, but better generate JSDoc for this interface? Then it'll be obvious with which type which parameters should go(also gateway and merchant id should be only with PAYMENT_GATEWAY which you didn't state here in comment)

2020-02-11 11:47 UTC, ivan3177 commented on android/src/main/java/com/busfor/RNGooglePayPackage.java
>  }
If you do refactor this file please add empty line at file end as GitHub warns here

2020-02-11 12:04 UTC, isokolovskii approved these changes

2020-02-12 08:49 UTC, merged

2020-12-21 18:01 UTC, jonzysim1 approved these changes